apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ekart-frontend
  template:
    metadata:
      labels:
        app: ekart-frontend
    spec:
      containers:
      - name: frontend
        image: yourdockerhub/ekart-frontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
