name: Auto Deploy Frontend to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install & Build React App
      run: |
        npm install
        npm run build

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/portfolio:latest

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

    - name: Set Image & Rollout
      run: |
        kubectl set image deployment/portfolio portfolio=${{ secrets.DOCKER_USERNAME }}/portfolio:latest
        kubectl rollout status deployment/portfolio
