name: Deploy Portfolio to Kubernetes

on:
  push:
    branches:
      - main  # or your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/portfolio:${{ github.sha }} .
          docker push your-dockerhub-username/portfolio:${{ github.sha }}

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/portfolio-deployment portfolio-container=your-dockerhub-username/portfolio:${{ github.sha }}
